// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WUxRf-pzqfSXMbj2j3IoW-uIdjlHf0U',
    appId: '1:74900399377:web:a26bf26f4cfefe48cb18b0',
    messagingSenderId: '74900399377',
    projectId: 'analytics-47024',
    authDomain: 'analytics-47024.firebaseapp.com',
    databaseURL: 'https://analytics-47024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'analytics-47024.appspot.com',
    measurementId: 'G-JBBQ5NBT01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWqIOkekX0WGY8wY-LysB23BPPlsgqaA',
    appId: '1:74900399377:android:5877ccb6742ef053cb18b0',
    messagingSenderId: '74900399377',
    projectId: 'analytics-47024',
    databaseURL: 'https://analytics-47024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'analytics-47024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYzdX0oF7m9HzwMrZaJZdAnPSRRVhxDik',
    appId: '1:74900399377:ios:bea33e8e0d11f366cb18b0',
    messagingSenderId: '74900399377',
    projectId: 'analytics-47024',
    databaseURL: 'https://analytics-47024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'analytics-47024.appspot.com',
    iosBundleId: 'com.flattrade.analytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYzdX0oF7m9HzwMrZaJZdAnPSRRVhxDik',
    appId: '1:74900399377:ios:021f1cef6aabff5acb18b0',
    messagingSenderId: '74900399377',
    projectId: 'analytics-47024',
    databaseURL: 'https://analytics-47024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'analytics-47024.appspot.com',
    iosBundleId: 'com.flattrade.analytics.RunnerTests',
  );
}
