// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKwBrKcWI1ykRE2JGFOgLnjtgaeKSobw',
    appId: '1:282664896557:web:d46457b8f21ecdf9f190a4',
    messagingSenderId: '282664896557',
    projectId: 'e-commerce-47b96',
    authDomain: 'e-commerce-47b96.firebaseapp.com',
    storageBucket: 'e-commerce-47b96.appspot.com',
    measurementId: 'G-2WZGHX4DVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeLx6avw4fXq3w5jArzyn25JILOAAqMj4',
    appId: '1:282664896557:android:5194cc06e4265184f190a4',
    messagingSenderId: '282664896557',
    projectId: 'e-commerce-47b96',
    storageBucket: 'e-commerce-47b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBceUE3psUEmKNSazZmqLs7K0u1UTvRcio',
    appId: '1:282664896557:ios:bcf88c115550adc2f190a4',
    messagingSenderId: '282664896557',
    projectId: 'e-commerce-47b96',
    storageBucket: 'e-commerce-47b96.appspot.com',
    iosBundleId: 'com.example.footwareadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBceUE3psUEmKNSazZmqLs7K0u1UTvRcio',
    appId: '1:282664896557:ios:bcf88c115550adc2f190a4',
    messagingSenderId: '282664896557',
    projectId: 'e-commerce-47b96',
    storageBucket: 'e-commerce-47b96.appspot.com',
    iosBundleId: 'com.example.footwareadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqKwBrKcWI1ykRE2JGFOgLnjtgaeKSobw',
    appId: '1:282664896557:web:72482e4aef0ab17af190a4',
    messagingSenderId: '282664896557',
    projectId: 'e-commerce-47b96',
    authDomain: 'e-commerce-47b96.firebaseapp.com',
    storageBucket: 'e-commerce-47b96.appspot.com',
    measurementId: 'G-917SDC3ZKF',
  );
}
