// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVXrtRB0EjJRmgWk-DKK0wCHpUbDDc0Y',
    appId: '1:354189681772:web:e8fb1993d3b9ac5a2a2449',
    messagingSenderId: '354189681772',
    projectId: 'ekyc-d40ab',
    authDomain: 'ekyc-d40ab.firebaseapp.com',
    storageBucket: 'ekyc-d40ab.appspot.com',
    measurementId: 'G-Y44YZDT1TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4xXa9bXaodq2HrugN-4gnJihGETgNdPg',
    appId: '1:354189681772:android:7c5ea99c8ef44dae2a2449',
    messagingSenderId: '354189681772',
    projectId: 'ekyc-d40ab',
    storageBucket: 'ekyc-d40ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8ZbGOefzF-GrtDhJC-b_l2tV79ZLnC4',
    appId: '1:354189681772:ios:801ba19631a5b63b2a2449',
    messagingSenderId: '354189681772',
    projectId: 'ekyc-d40ab',
    storageBucket: 'ekyc-d40ab.appspot.com',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO8ZbGOefzF-GrtDhJC-b_l2tV79ZLnC4',
    appId: '1:354189681772:ios:801ba19631a5b63b2a2449',
    messagingSenderId: '354189681772',
    projectId: 'ekyc-d40ab',
    storageBucket: 'ekyc-d40ab.appspot.com',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkVXrtRB0EjJRmgWk-DKK0wCHpUbDDc0Y',
    appId: '1:354189681772:web:55f0c63d9c72dc0b2a2449',
    messagingSenderId: '354189681772',
    projectId: 'ekyc-d40ab',
    authDomain: 'ekyc-d40ab.firebaseapp.com',
    storageBucket: 'ekyc-d40ab.appspot.com',
    measurementId: 'G-X62VKHG5CX',
  );

}