// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlAt9FRhwsL9mZZ9K6ivIC7s5PW7yWM18',
    appId: '1:108018298080:web:256db94752a059d0c0f485',
    messagingSenderId: '108018298080',
    projectId: 'userdetails-d890d',
    authDomain: 'userdetails-d890d.firebaseapp.com',
    storageBucket: 'userdetails-d890d.appspot.com',
    measurementId: 'G-CR34E9N9D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RSZrFz3oo9ok8M7_L5zKtuyWiNihNHE',
    appId: '1:108018298080:android:ecbf40f2465f2f50c0f485',
    messagingSenderId: '108018298080',
    projectId: 'userdetails-d890d',
    storageBucket: 'userdetails-d890d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdqy8o0Bjz523F1RrEPc5KO7dipXBdd7E',
    appId: '1:108018298080:ios:6664e121187aedd7c0f485',
    messagingSenderId: '108018298080',
    projectId: 'userdetails-d890d',
    storageBucket: 'userdetails-d890d.appspot.com',
    iosBundleId: 'com.example.firestorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdqy8o0Bjz523F1RrEPc5KO7dipXBdd7E',
    appId: '1:108018298080:ios:ab7366edcbb4f367c0f485',
    messagingSenderId: '108018298080',
    projectId: 'userdetails-d890d',
    storageBucket: 'userdetails-d890d.appspot.com',
    iosBundleId: 'com.example.firestorage.RunnerTests',
  );
}
