// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHbIsLkMEQt1wGLvHlabPfAredYmU1COo',
    appId: '1:65701061593:web:9c4f955753fb6928e52fc8',
    messagingSenderId: '65701061593',
    projectId: 'otpautofill-53fc1',
    authDomain: 'otpautofill-53fc1.firebaseapp.com',
    storageBucket: 'otpautofill-53fc1.appspot.com',
    measurementId: 'G-S0D1KSNTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9jOhxCOyiVqbiwcYB-W86fSqaBjZ5gE',
    appId: '1:65701061593:android:fc829abdc673ca27e52fc8',
    messagingSenderId: '65701061593',
    projectId: 'otpautofill-53fc1',
    storageBucket: 'otpautofill-53fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBNmWH9YaneAj7JiXhdK6eieNrvFfKIE',
    appId: '1:65701061593:ios:ae023dc8b770c480e52fc8',
    messagingSenderId: '65701061593',
    projectId: 'otpautofill-53fc1',
    storageBucket: 'otpautofill-53fc1.appspot.com',
    iosBundleId: 'com.example.otpautofillfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBNmWH9YaneAj7JiXhdK6eieNrvFfKIE',
    appId: '1:65701061593:ios:13280d0dbdd98988e52fc8',
    messagingSenderId: '65701061593',
    projectId: 'otpautofill-53fc1',
    storageBucket: 'otpautofill-53fc1.appspot.com',
    iosBundleId: 'com.example.otpautofillfirebase.RunnerTests',
  );
}
