// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpF241wkPgSUAV8mN8VPubMo973UFx3jw',
    appId: '1:423560250861:web:c53d560ee9f4b5c07313e4',
    messagingSenderId: '423560250861',
    projectId: 'fireb-ab820',
    authDomain: 'fireb-ab820.firebaseapp.com',
    storageBucket: 'fireb-ab820.appspot.com',
    measurementId: 'G-48S5EDCR3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh9nHSSMnt9-mYytHRBRvYzuucTLXwA2w',
    appId: '1:423560250861:android:36a2f1eabde69eb67313e4',
    messagingSenderId: '423560250861',
    projectId: 'fireb-ab820',
    storageBucket: 'fireb-ab820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpM-RiEPV-EOZ88nPCToUOXOIu0TKG3Bg',
    appId: '1:423560250861:ios:7b88477be6036fd67313e4',
    messagingSenderId: '423560250861',
    projectId: 'fireb-ab820',
    storageBucket: 'fireb-ab820.appspot.com',
    iosBundleId: 'com.example.fireb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpM-RiEPV-EOZ88nPCToUOXOIu0TKG3Bg',
    appId: '1:423560250861:ios:b071a9afb10aabcf7313e4',
    messagingSenderId: '423560250861',
    projectId: 'fireb-ab820',
    storageBucket: 'fireb-ab820.appspot.com',
    iosBundleId: 'com.example.fireb.RunnerTests',
  );
}
